Vagrant.configure(2) do |config|
  #config.vm.box = "centos/7"
  config.vm.box = "debian/jessie64"
  #config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "apricot"
  config.vm.network "public_network"
  # config.vm.network :forwarded_port, guest: 80, host: 8931, auto_correct: true
  # config.vm.synced_folder "./", "/var/www", create: true, group: "www-data", owner: "www-data"
  config.vm.provision "shell", path: "debian8_pxe.sh"
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
end
